version: '2'
 
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass 
      - MYSQL_DATABASE=waregym
    networks:
      - spring_mysql_network
    healthcheck:
      test: curl --fail -s http://localhost:3306/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 10
    ports:
      - "3306:3306"
    logging:
       driver: json-file
 
  web_server:
    depends_on:
      - mysql
      condition: service_healthy
    image: web_server
    container_name: web_server
    ports:
      - 8443:8443
    links:
      - mysql:mysql
    networks:
      - spring_mysql_network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test
      - SPRING_DATASOURCE_USER=user
      - SPRING_DATASOURCE_PASS=pass

networks:
  spring_mysql_network:
    driver: bridge


