version: '3.3'

services: 

  db:
    image: mysql:latest
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: pass
       MYSQL_DATABASE: waregym
       MYSQL_USER: root
       MYSQL_PASSWORD: pass
    
  spring:
    image: hervas/waregym:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8443
    environment:
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
