version: '2.3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.6.26
    volumes:
      - ./app/db:/var/lib/mysql
    environment:
       - MYSQL_ROOT_PASSWORD=pass
       - MYSQL_DATABASE=waregym
       - MYSQL_USER=root
       - MYSQL_PASSWORD=pass
    ports:
      - "3306:3306"
    logging:
      driver: json-file
    healthcheck:
      test: mysqladmin ping -h localhost
      timeout: 5s
      retries: 10

  app:
    container_name: waregym 
    image: waregym:dev
    volumes:
      - ./app/data:/app/uploaded
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "80:80"
    environment:
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create
    links:
      - mysql:mysql
    logging:
      driver: json-file
