version: '3.3'

services: 

  db:
    image: mysql:latest
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: pass
       MYSQL_DATABASE: waregym
       MYSQL_USER: root
       MYSQL_PASSWORD: pass
    
  spring:
    #image: waregym:final
    image: contruco/prueba:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8443:8443
    environment:
      ## - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/pott
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
